version: '3.6'
services:
  db:
    image: postgres:12.3-alpine
    container_name: jupiter_bank_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jupiterbank
    ports:
      - "5445:5432"